### ISSUE TITLE
Release v5

### ISSUE THREAD

**Issue by munk** [yodle/docker-registry-client#34]
Update version number
Update changelog
Publish

**Comment by graingert** [comment]
Checkout zest.releaser for automating this

**Comment by graingert** [comment]
@munk what's this release blocked on?

**Comment by munk** [comment]
@graingert just my available time. If you need the new release asap, I can take care of that this morning.

**Comment by graingert** [comment]
@munk that would be awsome

**Comment by munk** [comment]
@graingert When I use zest.releaser, I get an error. Have you seen this before?

```
Upload to pypi (Y/n)? y

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/release", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zest/releaser/release.py", line 320, in main
    releaser.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zest/releaser/baserelease.py", line 353, in run
    self.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zest/releaser/release.py", line 69, in execute
    self._release()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zest/releaser/release.py", line 305, in _release
    self._upload_distributions(package)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zest/releaser/release.py", line 163, in _upload_distributions
    self._retry_twine('upload', server, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zest/releaser/release.py", line 189, in _retry_twine
    if repository.package_is_uploaded(package_file):
AttributeError: 'Repository' object has no attribute 'package_is_uploaded'
```

**Comment by munk** [comment]
I published manually. Please let me know if anything isn't in order! https://pypi.python.org/pypi/docker-registry-client/0.5.0

**Comment by graingert** [comment]
it looks like you've got zest installed globally, you should be doing:

```shell
mkdir ~/.virtualenvs/
python3 -m venv ~/.virtualenvs/releaser
source ~/.virtualenvs/releaser/bin/activate
pip install -U pip setuptools wheel
pip install zest.releaser
fullrelease
```
